
#the config value publish-schedule is a CRON expression
#The pattern is a list of six single space-separated fields:
#representing second, minute, hour, day, month, weekday.
#Month and weekday names can be given as the first three letters of the English names.
#https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html

cloud:
  stream:
    bindings:
      temporalEvents:
        binder: rabbit
clusterName: clockCluster
endpoints:
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  configprops:
    enabled: true
    sensitive: false

---
spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
schedule: 0 0/1 * * * * # publish ever minute

---
spring:
  profiles: cloud
  rabbitmq:
    host: ${cloud.services.rabbitmq.connection.host}
    port: 5672
    username: ${cloud.services.rabbitmq.connection.username}
    password: ${cloud.services.rabbitmq.connection.password}
    virtual-host: ${cloud.services.rabbitmq.connection.virtualhost}
schedule: 0 0/15 * * * * # publish ever 15 minutes
# see https://docs.pivotal.io/pivotalcf/2-0/buildpacks/java/configuring-service-connections/spring-service-bindings.html#properties

---
spring:
  profiles: test
schedule: 0 0/1 * * * * # publish ever minute starting at the top of the hour
